# Create new session with <prefix>m
bind m display-popup \
    -d "#{pane_current_path}" \
    -xC \
    -yC \
    -w 40% \
    -h 3 \
    -E 'bash -i -c "tput setaf 2; \
        echo -n \"  \"; \
        tput sgr0; \
        read -p \"New session name: \" name; \
        tmux new-session -d -s \$name \
        && tmux switch-client -t \$name"'

# List sessions in fzf with <prefix>` (backtick)
bind ` display-popup \
    -E "tmux list-sessions -F '#S' \
    | grep -v $(tmux display-message -p '#S') \
    | fzf --reverse --preview='tmux capture-pane -pe -t {} | bat -p' \
    | xargs tmux switch-client -t"

# Kill sessions in fzf with <prefix>X
bind X display-popup \
    -E "tmux list-sessions -F '#S' \
    | grep -v $(tmux display-message -p '#S') \
    | fzf --reverse --preview='tmux capture-pane -pe -t {} | bat -p' \
    | xargs tmux kill-session -t"

# Open popup shell window with <prefix>!
bind ! display-popup \
    -d "#{pane_current_path}" \
    -xC \
    -yC \
    -w 60% \
    -h 75% \
    -E 'echo ">>> Ctrl-D to exit" && echo && $SHELL'

# Open popup Node window with <prefix>j
bind j display-popup \
    -d "#{pane_current_path}" \
    -xC \
    -yC \
    -w 60% \
    -h 75% \
    -E 'mise exec node -- node'

# Toggle popup floating shell with <prefix>f
# Detach if already inside scratch session, otherwise open popup
bind f if-shell '[ "#{session_name}" = "scratch" ]' \
    'detach-client' \
    'display-popup -d "#{pane_current_path}" -xC -yC -w 80% -h 75% -b rounded -E "tmux new-session -A -s scratch"'

# Open popup lazygit window with <prefix>g
bind g display-popup \
    -d "#{pane_current_path}" \
    -xC \
    -yC \
    -w 80% \
    -h 75% \
    -E 'lazygit'

# Open popup GitHub Dash window with <prefix>G
bind G display-popup \
    -d "#{pane_current_path}" \
    -xC \
    -yC \
    -w 80% \
    -h 75% \
    -E 'gh dash'
